### ISSUE TITLE
Can you give the specific versions of each package in the requirements.txt file?

### ISSUE THREAD

**Issue by yanfan7** [AnFreTh/NAMpy#10]
Can you give the specific versions of each package in the requirements.txt file? When I run "from nampy.models import NAM", an error "AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'" is reported. It may be caused by the incompatibility of tensorflow and keras versions. Can you give the specific version? This is very important to me, thanks!

**Comment by AnFreTh** [comment]
Could you provide your tensorflow, keras and tensorflow_probability versions when you encounter the error?

Also the python version and the operating system.

**Comment by yanfan7** [comment]
I have solved it, I downgraded tensorflow_probability from 0.24.0 to 0.23.0, the version of the package I am using now is as follows:
python== 3.9.19
tensorflow==2.15.1
tensorflow-intel==2.15.1
tensorflow-probability==0.23.0
keras==2.15.0
can now run it successfully, thanks！
